### ISSUE TITLE
Fix device discovery bug where a disk without wwn id is showing up

### ISSUE THREAD

**Issue by darkdoc** [openshift-storage-scale/openshift-fusion-access-operator#223]
```
apiVersion: fusion.storage.openshift.io/v1alpha1
kind: LocalVolumeDiscoveryResult
status:
  discoveredDevices:
  - WWN: ""
    deviceID: ""
    model: ""
    path: /dev/dmpconfig
    size: 0
    type: disk
    vendor: ""
  discoveredTimeStamp: "2025-04-16T13:51:33Z"
```
This disk should never show up as discovered device, since it has no wwn, and 0 size
